{{ if eq .Values.env "dev" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
{{ include "sbomer.labels" (list . "db") | indent 2 }}
spec:
  selector:
{{ include "sbomer.selector" (list . "db") | indent 4 }}
  type: ClusterIP
  ports:
    - name: http
      port: 5432
{{ end }}