apiVersion: v1
kind: Service
metadata:
  name: sbomer-postgres
  labels:
    app.kubernetes.io/component: "database"
spec:
  selector:
    app.kubernetes.io/component: "database"
  ports:
    - name: http
      port: 5432
