{{ if eq .Values.env "dev" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-sboms
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/sbomer"
{{ end }}