{{ if ne .Values.env "dev" }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}
{{ include "sbomer.labels" (list . "service") | indent 2 }}
spec:
{{ if eq .Values.env "stage" }}
    host: "sbomer-stage.apps.ocp-c1.prod.psi.redhat.com"
{{ else }}
    host: "sbomer.apps.ocp-c1.prod.psi.redhat.com"
{{ end }}
  to:
    kind: Service
    name: {{ .Release.Name }}-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
{{ end }}