quarkus:
  container-image:
    image: quay.io/goldmann/sbomer:latest
  swagger-ui:
    always-include: true
    path: /api

"%dev":
  quarkus:
    datasource:
      db-kind: postgresql
      username: username
      password: password
      jdbc:
        url: jdbc:postgresql://localhost:5432/sbomer

    hibernate-orm:
      database:
        generation: drop-and-create
      log:
        sql: true