quarkus:
  container-image:
    image: quay.io/goldmann/sbomer:latest
  swagger-ui:
    always-include: true
    path: /api
  datasource:
    db-kind: postgresql

  hibernate-orm:
    database:
      generation: create
    log:
      sql: true

"%dev":
  quarkus:
    datasource:
      username: username
      password: password
      jdbc:
        url: jdbc:postgresql://localhost:5432/sbomer

    hibernate-orm:
      database:
        generation: drop-and-create
      log:
        sql: true