#
# JBoss, Home of Professional Open Source.
# Copyright 2023 Red Hat, Inc., and individual contributors
# as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

quarkus:
  swagger-ui:
    always-include: true
    path: /api
  datasource:
    db-kind: postgresql
  smallrye-openapi:
    info-title: SBOMer service
  hibernate-orm:
    database:
      generation: update
  qpid-jms:
    url: "${UMB_BROKER_URL}"
  log:
    level: INFO
    category:
      "org.jboss.sbomer":
        level: DEBUG

sbomer:
  # List of all feature flags supported in SBOMer
  features:
    # UMB feature
    umb:
      # Global filter on the UMB support. If disabled -- all features below will be disabled as well.
      enabled: true
      consumer:
        enabled: false
        topic: "${CONSUMER_TOPIC}"
        # Defines which UMB messages received should result in SBOM generation. Accepted values are:
        # * all -- every message will result in SBOM generation
        # * product -- only Builds that are related to a Product will be triggerring SBOM generation
        trigger: product
      producer:
        enabled: false
        topic: "${PRODUCER_TOPIC}"
  domino:
    default-version: "0.0.86"
    additional-args: "--include-non-managed"
  cyclonedx:
    default-version: "2.7.7"
    additional-args: "--batch-mode --no-transfer-progress --quiet"

"%dev":
  quarkus:
    devservices:
      enabled: false
    # class-loading:
    #  parent-first-artifacts: io.quarkus:quarkus-bootstrap-maven-resolver
    datasource:
      username: username
      password: password
      jdbc:
        url: jdbc:postgresql://localhost:5432/sbomer
    hibernate-orm:
      database:
        generation: update
      log:
        sql: true
    smallrye-openapi:
      info-title: SBOMer service (development)
    qpid-jms:
      url: amqp://localhost:5672
      username: ""
      password: ""

  sbomer:
    features:
      umb:
        enabled: false
        consumer:
          enabled: false
        producer:
          enabled: false
    domino:
      default-version: "0.0.86"
      additional-args: "--include-non-managed"
    cyclonedx:
      default-version: "2.7.7"
      additional-args: "--batch-mode --no-transfer-progress"

"%test":
  quarkus:
    devservices:
      enabled: false
    datasource:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:init.sql'
    hibernate-orm:
      database:
        generation: drop-and-create
    qpid-jms:
      url: amqp://localhost:5672
      username: ""
      password: ""

  sbomer:
    features:
      umb:
        enabled: true
        consumer:
          enabled: true
          topic: "Consumer.pncsbomer.testing.VirtualTopic.eng.pnc.>"
        producer:
          enabled: false
    domino:
      default-version: "0.0.86"
      additional-args: "--include-non-managed"
    cyclonedx:
      default-version: "2.7.7"
      additional-args: "--batch-mode --no-transfer-progress"
