apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    sbomer-secret: sbomer-sso-clients
  name: sbomer-generate
{{ include "sbomer.labels" (list .) | indent 2 }}
spec:
  params:
    - name: env-config
      type: string
      description: "Environment configuration"
    - name: config
      type: string
      description: "Runtime generation configuration"
    - name: index
      type: string
      description: "Index to select which product should the SBOM be generated for"
  steps:
    - name: generate
      image: {{ .Values.generator.image.repository }}:{{ .Values.generator.image.tag }}
      imagePullPolicy: {{ .Values.generator.image.pullPolicy }}
      resources:
        limits:
          cpu: 1000m
          memory: 1000Mi
        requests:
          cpu: 200m
          memory: 300Mi
      env:
        - name: SBOMER_HOST
          value: {{ include "sbomer.serviceUrl" . }}
        - name: SBOMER_PNC_HOST
          value: {{ .Values.pnc.host }}
        - name: SBOMER_GERRIT_HOST
          value: {{ .Values.gerrit.host }}
        - name: SBOMER_INDY_HOST
          value: {{ .Values.indy.host }}
        - name: SBOMER_KOJI_HUB_HOST
          value: {{ .Values.koji.hub.host }}
        - name: SBOMER_KOJI_WEB_HOST
          value: {{ .Values.koji.web.host }}
        - name: SBOMER_PNC_PRODUCT_MAPPING
          value: {{ include "sbomer.productMapping" . }}
{{- if ne .Values.env "dev" }}
        - name: QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL
          value: {{ .Values.oidc.auth.server.url }}
        - name: QUARKUS_OIDC_CLIENT_CLIENT_ID
          value: {{ .Values.oidc.client.id }}
        - name: SBOMER_SECRET_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['sbomer-secret']
{{- end }}
        - name: APP_ENV
          value: {{ .Values.env }}

      script: |
        #!/usr/bin/env bash

        set -e
        set -x
        set -o pipefail

        if [ x"${APP_ENV}" == "xdev" ]; then
          export QUARKUS_OIDC_CLIENT_CLIENT_ENABLED=false
        fi

        if [ -n "${SBOMER_SECRET_NAME}" ]; then
          export QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET="$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/pnc-sbomer-client.secret)"
        fi

        CONFIG_PATH="/workdir/config.yaml"
        ENV_CONFIG_PATH="/workdir/env-config.yaml"

        # Set the path to Maven settings.xml file so that it can be used by the generator
        export SBOMER_MAVEN_SETTINGS_XML_PATH="/workdir/settings.xml"
        # Set the path to Gradle init script file so that it can be used by the generator
        export SBOMER_GRADLE_SETTINGS_XML_PATH="/workdir/cyclonedx-init.gradle"

        source /workdir/.sdkman/bin/sdkman-init.sh

        export MAVEN_OPTS="-Xms256m -Xmx512m"

        echo "Storing configuration in the $CONFIG_PATH file"
        echo "$(params.config)" | tee $CONFIG_PATH

        echo "Storing environment configuration in the $ENV_CONFIG_PATH file"
        echo "$(params.env-config)" | tee $ENV_CONFIG_PATH

        echo "Parsing the environment config file...."
        # Read the YAML file and iterate through its entries
        while IFS=':' read -r key value; do
           # Remove leading and trailing spaces from key and value
           key=$(echo "$key" | sed -e 's/^[ \t]*//' -e 's/[ \t]*$//')
           value=$(echo "$value" | sed -e 's/^[ \t]*//' -e 's/[ \t]*$//')

           # Check if the output is not empty
           if [ -n "$key" ]; then
              # Call the script with softwaretype and required_version as arguments
              best_available_version=$(/workdir/sdk_find_closest_installed_software.sh "$key" "$value" )
              # Now set the closest softwaretype to the required_version
              if [ -n "$best_available_version" ]; then
                 sdk use $key ${best_available_version}
              fi
           fi      
        done < /workdir/env-config.yaml

        mkdir -p $(workspaces.data.path)/$(context.taskRun.name)
        cd $(workspaces.data.path)/$(context.taskRun.name)

        echo "Running generation..."
        exec /workdir/.sdkman/candidates/java/17/bin/java -Duser.home=/workdir -Xms256m -Xmx512m -jar /workdir/generator/quarkus-run.jar -v sbom auto generate --workdir /tmp/sbomer-workdir --config $CONFIG_PATH --index "$(params.index)"
      volumeMounts:
        - name: secrets-workdir
          mountPath: /mnt/secrets
{{- if ne .Values.env "dev" }}
  sidecars:
    - image: quay.io/rh-newcastle/pnc-vault-secrets:1.0.1
      name: get-vault-secrets
      command:
        - /bin/bash
      args:
        - -c
        - cd /mnt/secrets;
          pnc-vault-secrets dump $(SBOMER_SECRET_NAME)-$(APP_ENV);
      env:
        - name: VAULT_ADDR
          valueFrom:
            secretKeyRef:
              name: vault-connection-info
              key: vault-address
        - name: VAULT_APP_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: vault-connection-info
              key: vault-app-role-id
        - name: VAULT_APP_SECRET_ID
          valueFrom:
            secretKeyRef:
              name: vault-connection-info
              key: vault-app-secret-id
        - name: SBOMER_SECRET_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['sbomer-secret']
        - name: APP_ENV
          value: {{ .Values.env }}
      volumeMounts:
        - name: secrets-workdir
          mountPath: /mnt/secrets
{{- end }}
  workspaces:
    - name: data
      description: Workspace used to store the generated SBOMs
  volumes:
    - name: secrets-workdir
      emptyDir:
        medium: Memory
