#
# JBoss, Home of Professional Open Source.
# Copyright 2023 Red Hat, Inc., and individual contributors
# as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sbomer-sa
  labels:
    app.kubernetes.io/component: "service"
imagePullSecrets:
  - name: sbomer-redhatio-pull-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sbomer
  labels:
    app.kubernetes.io/component: "service"
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create", "get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sbomer-pod-creator
  labels:
    app.kubernetes.io/component: "service"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sbomer
subjects:
  - kind: ServiceAccount
    name: sbomer-sa