apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sbomer-postgres
  labels:
    app.kubernetes.io/component: "database"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G
