env: prod

cache:
  storage:
    accessMode: ReadWriteOnce
  image:
    repository: quay.io/rh-newcastle/sbomer-cache

service:
  route: 
    enabled: true
  storage:
    accessMode: ReadWriteMany
  image:
    repository: quay.io/rh-newcastle/sbomer-service

generator:
  image:
    repository: quay.io/rh-newcastle/sbomer-generator
