env: prod

cache:
  image:
    repository: quay.io/rh-newcastle/sbomer-cache
    tag: latest
    pullPolicy: Always

service:
  image:
    repository: quay.io/rh-newcastle/sbomer-service
    tag: latest
    pullPolicy: Always

generator:
  image:
    repository: quay.io/rh-newcastle/sbomer-generator
    tag: latest
    pullPolicy: Always