env: prod

cache:
  image:
    repository: quay.io/rh-newcastle/sbomer-cache
    tag: latest
    pullPolicy: Always

service:
  route: 
    enabled: true
    host: "sbomer.apps.ocp-c1.prod.psi.redhat.com"
  storage:
    accessMode: ReadWriteMany
  image:
    repository: quay.io/rh-newcastle/sbomer-service
    tag: latest
    pullPolicy: Always

generator:
  image:
    repository: quay.io/rh-newcastle/sbomer-generator
    tag: latest
    pullPolicy: Always