env: stage

cache:
  storage:
    accessMode: ReadWriteMany
  image:
    repository: quay.io/rh-newcastle-stage/sbomer-cache
    tag: latest
    pullPolicy: Always

service:
  route:
    enabled: true
  storage:
    accessMode: ReadWriteMany
  image:
    repository: quay.io/rh-newcastle-stage/sbomer-service
    tag: latest
    pullPolicy: Always

generator:
  image:
    repository: quay.io/rh-newcastle-stage/sbomer-generator
    tag: latest
    pullPolicy: Always
