#
# JBoss, Home of Professional Open Source.
# Copyright 2023 Red Hat, Inc., and individual contributors
# as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sbomer-generate
spec:
  params:
    - name: config
      type: string
      description: "Runtime generation configuration"
    - name: index
      type: string
      description: "Index to select which product should the SBOM be generated for"
  steps:
    - name: generate
      image: sbomer-generator
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 1000m
          memory: 1000Mi
        requests:
          cpu: 200m
          memory: 300Mi
      env:
        - name: SBOMER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: sbomer-tekton
              key: SBOMER_SERVICE_URL
        - name: PNC_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: sbomer-tekton
              key: PNC_SERVICE_HOST
        - name: SBOMER_PRODUCT_MAPPING_ENV
          valueFrom:
            configMapKeyRef:
              name: sbomer-tekton
              key: SBOMER_PRODUCT_MAPPING_ENV
      script: |
        #!/usr/bin/env bash

        set -e
        set -x
        set -o pipefail

        CONFIG_PATH="/workdir/config.yaml"

        # Set the path to Maven settings.xml file so that ict can be used by the generator
        export SBOMER_MAVEN_SETTINGS_XML_PATH="/workdir/settings.xml"

        source /workdir/.sdkman/bin/sdkman-init.sh

        export MAVEN_OPTS="-Xms256m -Xmx512m"

        echo "Storing configuration in the $CONFIG_PATH file"
        echo "$(params.config)" | tee $CONFIG_PATH

        echo "Running generation..."
        exec /workdir/.sdkman/candidates/java/17/bin/java -Xms256m -Xmx512m -jar ./generator/quarkus-run.jar -v sbom auto generate --config $CONFIG_PATH --index "$(params.index)"

