#
# JBoss, Home of Professional Open Source.
# Copyright 2023 Red Hat, Inc., and individual contributors
# as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##
# PRODUCTION OVERLAY
#
# This overlay deploys the full service using images from our CI
# on a production OpenShift environment.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../targets/ocp
patchesStrategicMerge:
  - patches/tekton/cm.yaml
patches:
  # - target:
  #     kind: Deployment
  #     name: sbomer-cache
  #   patch: |-
  #     - op: add
  #       path: /spec/template/spec/containers/0/env/-
  #       value:
  #         name: PNC_SERVICE_HOST
  #         value: "orch.psi.redhat.com"
  #     - op: add
  #       path: /spec/template/spec/containers/0/env/-
  #       value:
  #         name: INDY_REPOSITORY_HOST
  #         value: "indy.psi.redhat.com"
  - target:
      kind: Deployment
      name: sbomer
    patch: |-
      - op: add
        path: /spec/template/spec/initContainers/-
        value:
          image: quay.io/rh-newcastle/pnc-vault-secrets:1.0.0
          name: get-vault-secrets
          resources:
            limits:
              cpu: 0.2
              memory: 200Mi
            requests:
              cpu: 0.2
              memory: 200Mi
          command:
            - /bin/bash
          args:
            - -c
            - cd /mnt/secrets;
              pnc-vault-secrets dump $(SBOMER_SECRET_NAME)-$(APP_ENV);
              echo "#!/bin/bash" >> /mnt/secrets/env.sh;
              echo "export CONSUMER_TOPIC=\"$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/consumer.topic)\"" >> /mnt/secrets/env.sh;
              echo "export PRODUCER_TOPIC=\"$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/producer.topic)\"" >> /mnt/secrets/env.sh;
              echo "export UMB_BROKER_URL=\"$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/qpid-jms.url)\"" >> /mnt/secrets/env.sh;
              echo "export QUARKUS_OIDC_AUTH_SERVER_URL=\"$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/auth-server-url.txt)\"" >> /mnt/secrets/env.sh;
              echo "export QUARKUS_DATASOURCE_USERNAME=\"$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/datasource.user)\"" >> /mnt/secrets/env.sh;
              echo "export QUARKUS_DATASOURCE_PASSWORD=\"$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/datasource.password)\"" >> /mnt/secrets/env.sh;
              echo "export QUARKUS_DATASOURCE_JDBC_URL=\"$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/datasource.connection)\"" >> /mnt/secrets/env.sh;
              echo "export KEYSTORE_PASSWORD=\"$(cat /mnt/secrets/${SBOMER_SECRET_NAME}-${APP_ENV}/${APP_ENV}-pnc-sbomer.password)\"" >> /mnt/secrets/env.sh;
              source /mnt/secrets/env.sh;
          env:
            - name: VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: vault-connection-info
                  key: vault-address
            - name: VAULT_APP_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: vault-connection-info
                  key: vault-app-role-id
            - name: VAULT_APP_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: vault-connection-info
                  key: vault-app-secret-id
            - name: SBOMER_SECRET_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['sbomer-secret']
            - name: APP_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['environment']
          volumeMounts:
            - name: secrets-workdir
              mountPath: /mnt/secrets
      - op: add
        path: /spec/template/metadata/annotations/environment
        value: prod
      - op: add
        path: /spec/template/metadata/annotations/sbomer-secret
        value: sbomer-secrets
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SBOMER_PRODUCT_MAPPING_ENV
          value: "production"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SBOMER_ROUTE_HOST
          value: "sbomer.apps.ocp-c1.prod.psi.redhat.com"
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 1000m
            memory: 2000Mi
          limits:
            cpu: 1000m
            memory: 2000Mi

  - target:
      kind: Route
    patch: |-
      - op: replace
        path: /spec/host
        value: "sbomer.apps.ocp-c1.prod.psi.redhat.com"


# List of images used in production
# TODO: Currently happily using :latest tag but this will be changed in the future
images:
  - name: sbomer-generator
    newName: quay.io/rh-newcastle/sbomer-generator:latest
  - name: sbomer-service
    newName: quay.io/rh-newcastle/sbomer-service:latest
  - name: sbomer-cache
    newName: quay.io/rh-newcastle/sbomer-cache:latest
