apiVersion: v1
kind: ServiceAccount
metadata:
  name: sbomer-sa
  labels:
    app.kubernetes.io/component: "service"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sbomer
  labels:
    app.kubernetes.io/component: "service"
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create", "get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sbomer
subjects:
  - kind: ServiceAccount
    name: sbomer-sa
