apiVersion: v1
kind: Service
metadata:
  name: sbomer
  labels:
    app.kubernetes.io/component: "service"
spec:
  selector:
    app.kubernetes.io/component: "service"
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
