#
# JBoss, Home of Professional Open Source.
# Copyright 2023 Red Hat, Inc., and individual contributors
# as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sbomer-generate-cyclonedx
spec:
  params:
    - name: id
      type: string
      description: "The PNC build ID"
    # TODO: Currently that JSON is not really easy to work with in a Bash script, but this will change once we move to a proper CLI.
    - name: config
      type: string
      description: |
        Additional parameters that instrument the CycloneDX plugin in the JSON format:

        Currently only following keys are supported:

          * version:            Version of the Maven CycloneDX plugin, default: 2.7.5
          * additional-args:    Additional arguments passed to the Maven CycloneDX plugin invocation

        Example (and default):

        {"version": "2.7.5", "additional-args": "--batch-mode --no-transfer-progress --quiet"}
      default: |
        {"version": "2.7.5", "additional-args": "--batch-mode --no-transfer-progress --quiet"}


    # TODO: Content available below is not supported in the Tekton version we use.
    # For more information please refer to this TEP: https://github.com/tektoncd/community/blob/main/teps/0075-object-param-and-result-types.md

    # - name: config
    #   type: object
    #   description: |
    #     Additional parameters that instrument the CycloneDX plugin, available options:

    #     * version:            Version of the Maven CycloneDX plugin, default: 2.7.5
    #     * additional-args:    Additional arguments passed to the Maven CycloneDX plugin invocation
    #   properties:
    #     version:
    #      type: string
    #     additional-args:
    #      type: string
    #   default:
    #     version: "2.7.5"
    #     additional-args: "--batch-mode --no-transfer-progress --quiet"
  steps:
    - name: generate
      image: sbomer-generator
      imagePullPolicy: IfNotPresent
      env:
        - name: SBOMER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: sbomer-tekton
              key: SBOMER_SERVICE_URL
      script: |
        #!/usr/bin/env bash

        set -e

        source ~/.sdkman/bin/sdkman-init.sh

        sdk use maven 3.9

        echo '$(params.config)' | tee config.json
        TOOL_VERSION=$(cat config.json | jq --raw-output '.version')

        [[ -z "${SBOMER_SERVICE_URL}" ]] && SBOMER_SERVICE_URL="http://${SBOMER_SERVICE_HOST}:${SBOMER_SERVICE_PORT}"

        /workdir/.sdkman/candidates/java/17/bin/java -jar ./generator/quarkus-run.jar -v generate --sbom-id=$(params.id) maven cyclonedx --plugin-version=$TOOL_VERSION --target=$(workspaces.data.path)/source --settings=~/settings.xml
  workspaces:
    - name: data
